/**
 * Validates that an address is a real Bitcoin address
 * Rejects fake addresses generated by the custom canister
 * Supports both mainnet and testnet addresses
 */
export function isValidBitcoinAddress(address: string | null | undefined): boolean {
  if (!address || address.length === 0) {
    return false;
  }

  // Reject fake addresses that contain underscores or look like canister IDs
  // Fake addresses from custom canister look like: bc1q2en3s_2iaaa_aaaad_qhqja_cai
  if (address.includes('_') || address.match(/[a-z]{5}-[a-z]{5}-[a-z]{5}-[a-z]{5}-[a-z]{5}-[a-z]{5}-[a-z]{5}-[a-z]{5}-[a-z]{5}-[a-z]{5}-[a-z]{3}/)) {
    return false;
  }

  // Check if testnet mode is enabled
  const isTestnet = import.meta.env.VITE_USE_TESTNET === 'true';

  // Valid Bitcoin addresses:
  // Mainnet:
  // - '1' (legacy P2PKH)
  // - '3' (legacy P2SH)
  // - 'bc1' (Bech32/segwit)
  // - 'bc1p' (Bech32m/taproot)
  // Testnet:
  // - 'm' or 'n' (legacy P2PKH/P2SH)
  // - '2' (legacy P2SH)
  // - 'tb1' (Bech32/segwit)
  // - 'tb1p' (Bech32m/taproot)
  const mainnetPrefixes = /^(1|3|bc1)/i;
  const testnetPrefixes = /^(m|n|2|tb1)/i;
  
  if (isTestnet) {
    // In testnet mode, accept both testnet and mainnet addresses (for flexibility)
    if (!mainnetPrefixes.test(address) && !testnetPrefixes.test(address)) {
      return false;
    }
  } else {
    // In mainnet mode, only accept mainnet addresses
    if (!mainnetPrefixes.test(address)) {
      return false;
    }
  }

  // Basic length check (Bitcoin addresses are typically 26-62 characters)
  if (address.length < 26 || address.length > 62) {
    return false;
  }

  // Check for valid characters (alphanumeric, no special chars except for bech32)
  // Legacy addresses: base58 (no 0, O, I, l)
  // Bech32 addresses: alphanumeric lowercase
  if (address.startsWith('bc1') || address.startsWith('tb1')) {
    // Bech32 (mainnet or testnet): only lowercase alphanumeric
    if (!/^(bc1|tb1)[a-z0-9]+$/.test(address)) {
      return false;
    }
  } else {
    // Legacy: base58 characters only
    if (!/^[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]+$/.test(address)) {
      return false;
    }
  }

  return true;
}




